### PR TITLE
Upgrade Go to 1.19

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Upgrade Go to 1.19

#### Changes

- Change Go matrix in `test` and `build` workflows.

#### Testing

Should be covered by CI.

##### Regressions

Should be covered by tests.

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

### CODE REVIEW

**Review by adriansmares — APPROVED** [review]
Do we need a new Docker image as well ?

**Comment by KrishnaIyer** [comment]
Could be nice. I believe it's automatically done on a push to `master` based on the action?

**Comment by adriansmares** [comment]
Seems to be indeed. You should also update the version in `go.mod` and do a `go mod tidy`.

**Comment by KrishnaIyer** [comment]
Alright here it goes.

**Pull request merged**
